spring:
  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    url: jdbc:mysql://mysql:3306/local_database
    username: local_user
    password: local_password
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile

jwt:
  secret: 4f88a508694a765aaf62223cc79905cee97dafcac3f172c58ec5ea1f157a35001fd5e0bd33716c0d3fcfcc3f6a9aa6124b3b9367cd3cd6368c1df08b46584ece